"""empty message

Revision ID: 019a54a1046b
Revises: 48e221275c1d
Create Date: 2018-08-13 14:50:23.772995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019a54a1046b'
down_revision = '48e221275c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
