"""Added first and last name

Revision ID: 108b193343d3
Revises: 8d4ee1677fb2
Create Date: 2018-09-02 11:45:12.065477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108b193343d3'
down_revision = '8d4ee1677fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
