"""added user fields

Revision ID: 75b2b926d295
Revises: 0fa1361daf0c
Create Date: 2018-09-01 17:44:00.008705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b2b926d295'
down_revision = '0fa1361daf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('availability', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('skills', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skills')
    op.drop_column('user', 'location')
    op.drop_column('user', 'availability')
    # ### end Alembic commands ###
